#Modify Makefile for your instalation of SDL


#what compiler we are using
CC=x86_64-w64-mingw32-g++
#WINDRES=x86_64-w64-mingw32-windres
#the path to SDL config
SDLPATH=$(MINGW_PATH)/bin

all: hppd


doubleup.o: doubleup.cpp
	$(CC) doubleup.cpp -c `${SDLPATH}/sdl-config --cflags`
#rez.o:
#	$(WINDRES)  mp.rc -o rez.o

hppd: doubleup.o 
	$(CC) doubleup.o -o hppd.exe -static `${SDLPATH}/sdl-config --static-libs` -luser32 -lgdi32 -lwinmm
		

clean:
	rm -f *.o *~

